### ISSUE TITLE
Unable to start the app on real pepper

### ISSUE THREAD

**Issue by mforell** [aldebaran/qisdk-tutorials#7]
Hi guys, we just got a new Pepper at my university, but I am not able to run the app on a real Pepper. I can find the robot, but Android Studio has problems with the tablet. I think that I have to upgrade Pepper to version 1.9, but I can't find any information in the documentation on how to upgrade. Can you guys help me?

**Comment by maesho** [comment]
I think version 1.9 is hardware version.

**Comment by tcruzcast** [comment]
Hello @mforell 

Yes, that's right. This project is only compatible with Pepper 1.9 model.

Cheers!
